# Generated by Django 3.1.3 on 2021-02-13 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210125_2309'),
        ('post', '0002_post_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.language'),
            preserve_default=False,
        ),
    ]
