# Generated by Django 3.1.3 on 2021-01-25 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210125_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hometext',
            old_name='name',
            new_name='title',
        ),
    ]
