# Generated by Django 3.1.3 on 2021-03-02 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210125_2309'),
        ('home', '0003_auto_20210125_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometext',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.language'),
        ),
    ]
